[project]
name = "mitsuba3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "drjit>=1.2.0",
    "matplotlib>=3.10.8",
    "mitsuba>=3.7.1",
    "plotly>=6.5.2",
]
